# docker-compose.yml

version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    container_name: user-auth
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Sree
      - POSTGRES_DB=user-auth
    volumes:
      - user-auth:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  user-auth:
